
	CREATE TABLE IF NOT EXISTS USERS (
	id INTEGER PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	username TEXT  NOT NULL UNIQUE,
	user_password TEXT NOT NULL,
	profile_picture TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS SESSIONS (
	id TEXT PRIMARY KEY,
	user_id INTEGER NOT NULL,
	expires_at DATETIME NOT NULL,
	FOREIGN KEY (user_id) REFERENCES USERS (id)
	);
	
	CREATE TABLE IF NOT EXISTS POSTS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	content TEXT NOT NULL,
	picture_content TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES USERS (id) 
	);
	
	CREATE TABLE IF NOT EXISTS CATEGORIES (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS POST_CATEGORIES (
	post_id INTEGER NOT NULL,
	category_id INTEGER NOT NULL,
	PRIMARY KEY (post_id, category_id),
    FOREIGN KEY (post_id) REFERENCES POSTS (id),
    FOREIGN KEY (category_id) REFERENCES CATEGORIES (id)
	);

	CREATE TABLE IF NOT EXISTS POST_REACTIONS (
	post_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	reaction INTEGER CHECK (reaction IN (-1, 1)),
	PRIMARY KEY (post_id, user_id),
    FOREIGN KEY (post_id) REFERENCES POSTS (id),
    FOREIGN KEY (user_id) REFERENCES USERS (id) 
	);

	CREATE TABLE IF NOT EXISTS COMMENTS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	content TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES USERS (id),
	FOREIGN KEY (post_id) REFERENCES POSTS (id)
	);

	CREATE TABLE IF NOT EXISTS COMMENT_REACTION (
	user_id INTEGER NOT NULL,
	comment_id INTEGER NOT NULL,
	reaction INTEGER CHECK (reaction IN (-1, 1)),
	PRIMARY KEY (user_id, comment_id),
	FOREIGN KEY (user_id) REFERENCES USERS (id),
	FOREIGN KEY (comment_id) REFERENCES COMMENTS (id)
	);
